image: node:8.12.0

stages:
  - test

test_jest:
  stage: test
  script:
    - npm set registry https://registry.npmjs.org/
    - node -v
    - npm -v
    - npm i @types/node
  tags:
    - docker
  allow_failure: true
