image: node:8.9.0

before_script:
  - npm install

cache:
  paths:
    - node_modules/

stages:
  - test
  - deploy

test_jest:
  stage: test
  script:
    - npm test
  tags:
    - docker

ninja_deploy:
  stage: deploy
  script:
    - git push heroku master
  tags:
    - docker
