image: node:8.9.0

stages:
  - build
  - test
  - deploy

build_test:
  stage: build
  script:
    - node -v
    - npm -v
    - npm install
  tags:
    - docker

test_jest:
  stage: test
  script:
    - npm test
  tags:
    - docker

ninja_deploy:
  stage: deploy
  script:
    - git push heroku master
  tags:
    - docker
